main: main.cpp IteratorBase.cpp IteratorBase.h LinearDataStruct.cpp LinearDataStruct.h Queue.cpp Queue.h Stack.cpp Stack.h
	g++ main.cpp IteratorBase.cpp LinearDataStruct.cpp Queue.cpp Stack.cpp -g -o main
clean:
	rm *.o main